[package]
name = "tf2_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_builder = "0.20.0"
log = "0.4.22"
nalgebra = "0.33.0"
parking_lot = "0.12.3"
thiserror = "1.0.63"

[dev-dependencies]
approx = "0.5.1"
rand = "0.8.5"
serde = "1.0.210"
serde_yaml = "0.9.34"
